[build]
  # Build command for the frontend
  command = "npm run build"
  # Directory where the built files are located
  publish = "dist"
  # Functions directory
  functions = "netlify/functions"
  
  # Environment variables (you'll need to set these in Netlify dashboard)
  [build.environment]
    NODE_VERSION = "18"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  # Handle client-side routing - redirect all non-file requests to index.html
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"


